In [1]:
from google.cloud import bigquery

client = bigquery.Client()

#### Public dataset

In [16]:
# Performs a query
QUERY = (
    'SELECT * from `bigquery-public-data.usa_names.usa_1910_2013` '
    'WHERE state = "CA" '
    'LIMIT 5')

# API request
query_job = client.query(QUERY)

In [17]:
# Waits for query to finish
rows = query_job.result()

for row in rows:
    print(row)

Row(('CA', 'F', 1910, 'Ruth', 128), {'state': 0, 'gender': 1, 'year': 2, 'name': 3, 'number': 4})
Row(('CA', 'F', 1910, 'Virginia', 101), {'state': 0, 'gender': 1, 'year': 2, 'name': 3, 'number': 4})
Row(('CA', 'F', 1910, 'Elizabeth', 93), {'state': 0, 'gender': 1, 'year': 2, 'name': 3, 'number': 4})
Row(('CA', 'F', 1910, 'Louise', 67), {'state': 0, 'gender': 1, 'year': 2, 'name': 3, 'number': 4})
Row(('CA', 'F', 1910, 'Doris', 56), {'state': 0, 'gender': 1, 'year': 2, 'name': 3, 'number': 4})

In [18]:
df = query_job.to_dataframe()
df

  state gender  year       name  number
0    CA      F  1910       Ruth     128
1    CA      F  1910   Virginia     101
2    CA      F  1910  Elizabeth      93
3    CA      F  1910     Louise      67
4    CA      F  1910      Doris      56

---
**NOTE**

If you run a queries on private data using `client.query(QUERY)`, your identity should have the following IAM roles or similar:
- **At the project level**: *roles/bigquery.jobUser* (Lower resource is Project) that includes the *bigquery.jobs.create* permission.
- **At the dataset level**: *roles/bigquery.dataViewer* (Lower resource is Dataset) that includes *bigquery.tables.getData* permission.

---

In [11]:
# Displays credentials and scopes informations
client.__dict__['_credentials'].__dict__